In [5]:
import pandas as pd
data = pd.read_csv("Iris.csv")
data = data.drop("Id",axis=1)

In [6]:
x = data.drop("Species",axis=1)
x.head(5)

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0            5.1           3.5            1.4           0.2
1            4.9           3.0            1.4           0.2
2            4.7           3.2            1.3           0.2
3            4.6           3.1            1.5           0.2
4            5.0           3.6            1.4           0.2

In [7]:
y = data["Species"]
y.head(5)

0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: Species, dtype: object

In [26]:
from sklearn.model_selection import cross_val_score

# K-Nearest Neighbors

In [27]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
cross_val_score(knn,x,y,cv=5).mean()

np.float64(0.9733333333333334)

# Random Forest

In [28]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
cross_val_score(rf,x,y,cv=5).mean()

np.float64(0.9533333333333334)

# Naive Bayes

In [29]:
from sklearn.naive_bayes import GaussianNB
nb = GaussianNB()
cross_val_score(nb,x,y,cv=5).mean()

np.float64(0.9533333333333334)

# Support Vector Machine

In [30]:
from sklearn.svm import SVC
svm = SVC()
cross_val_score(svm,x,y,cv=5).mean()

np.float64(0.9666666666666666)