In [1]:
import numpy as np
import pandas as pd

In [3]:
data = pd.read_csv('kyphosis.csv')
data.head()

  Kyphosis  Age  Number  Start
0   absent   71       3      5
1   absent  158       3     14
2  present  128       4      5
3   absent    2       5      1
4   absent    1       4     15

In [4]:
data.shape

(81, 4)

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 81 entries, 0 to 80
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Kyphosis  81 non-null     object
 1   Age       81 non-null     int64
 2   Number    81 non-null     int64
 3   Start     81 non-null     int64
dtypes: int64(3), object(1)
memory usage: 2.7+ KB

In [6]:
x = data.drop('Kyphosis', axis=1)

In [7]:
x.head()

   Age  Number  Start
0   71       3      5
1  158       3     14
2  128       4      5
3    2       5      1
4    1       4     15

In [8]:
y = data['Kyphosis']

In [9]:
y.head()

0     absent
1     absent
2    present
3     absent
4     absent
Name: Kyphosis, dtype: object

In [10]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3)

In [11]:
x_train.shape

(56, 3)

In [12]:
x_test.shape

(25, 3)

Decision Treee

In [13]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
model.fit(x_train, y_train)

DecisionTreeClassifier()

In [16]:
pred =model.predict(x_test)
pred

array(['absent', 'present', 'present', 'absent', 'absent', 'absent',
       'present', 'absent', 'absent', 'absent', 'absent', 'absent',
       'absent', 'absent', 'absent', 'present', 'present', 'absent',
       'absent', 'absent', 'absent', 'absent', 'present', 'present',
       'absent'], dtype=object)

In [15]:
y_test

65     absent
73     absent
52    present
79    present
19     absent
7      absent
31     absent
64     absent
46     absent
15     absent
10    present
3      absent
49     absent
32     absent
70     absent
34     absent
21    present
66     absent
17     absent
41     absent
24    present
37    present
71     absent
61    present
5      absent
Name: Kyphosis, dtype: object

In [17]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, pred)

0.68

In [18]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, pred)

array([[14,  4],
       [ 4,  3]])

Rando forest
**bold text**

In [13]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators=50)
model.fit(x_train, y_train)

RandomForestClassifier(n_estimators=50)

In [14]:
pred =model.predict(x_test)
pred

array(['absent', 'absent', 'absent', 'absent', 'absent', 'absent',
       'absent', 'absent', 'absent', 'absent', 'absent', 'absent',
       'absent', 'absent', 'absent', 'absent', 'absent', 'absent',
       'absent', 'absent', 'present', 'absent', 'absent', 'present',
       'absent'], dtype=object)

In [15]:
y_test

19     absent
52    present
30     absent
41     absent
67     absent
49     absent
26     absent
27     absent
29     absent
54     absent
23     absent
53     absent
7      absent
48    present
10    present
69     absent
20     absent
4      absent
9     present
33     absent
79    present
76    present
45    present
61    present
14     absent
Name: Kyphosis, dtype: object

In [16]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, pred)

0.76

In [17]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, pred)

array([[17,  0],
       [ 6,  2]])